#!/usr/bin/env python3
"""Write docs/generated/budgets.md: the preregistered T(n) per family and ladder rung (D3).

Usage: python3 scripts/build_budgets.py
Deterministic (1000 instances per cell, seed 0); the preregistration cites this file,
never hand-typed values (review R3: documented T(n) disagreed with the code).
"""
import math
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
from ngs.budget import budget  # noqa: E402

LADDERS = {
    "reachability": (16, 1024),
    "shortest_path": (16, 1024),
    "maze": (9, 33),
    "sorting": (16, 256),
    "associative_recall": (16, 256),
    "automaton": (16, 512),
}


def ladder(lo: int, hi: int) -> list[int]:
    out, j = [], 0
    while True:
        n = round(lo * 2 ** (j / 2))
        if n > hi:
            break
        out.append(n if n % 2 or lo % 2 == 0 else n + 1)   # odd sides stay odd for mazes
        j += 1
    return sorted(set(out))


def main() -> None:
    lines = ["# Preregistered iteration budgets T(n) (generated by scripts/build_budgets.py; do not edit)", "",
             "T(n) = max(4, ceil(1.5 × q99 of required steps)) over 1000 instances, seed 0 (D3).", "",
             "| Family | n → T(n) |", "|---|---|"]
    for family, (lo, hi) in LADDERS.items():
        cells = []
        rungs = [9, 13, 17, 25, 33] if family == "maze" else ladder(lo, hi)
        for n in rungs:
            samples = 1000 if family not in ("maze",) or n <= 17 else 300
            cells.append(f"{n} → {budget(family, n, samples=samples)}")
        lines.append(f"| {family} | {' · '.join(cells)} |")
    lines += ["", "Maze rungs above side 17 use 300 instances (cost); every other cell uses 1000. Maze sides chosen: 9, 13, 17, 25, 33.",
              "Small non-monotonicities between adjacent rungs (e.g. reachability) are q99 sampling noise and are kept as generated, not smoothed."]
    out = Path(__file__).resolve().parent.parent / "docs" / "generated" / "budgets.md"
    out.write_text("\n".join(lines) + "\n")
    print(out.read_text())


if __name__ == "__main__":
    main()
